import materials_engineering_mechanical_behavior_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace materials_engineering_mechanical_behavior_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end materials_engineering_mechanical_behavior_lemma_canonical_lane_mathlib
end HautevilleHouse
